format = "$hostname$directory( $git_branch)( $git_status)$character"
# format = "$hostname$directory$git_branch $character"
right_format = "$python$time$cmd_duration$status"

add_newline = false

[character]
success_symbol = " [»](bold green)"
error_symbol = " [»](red)"
vimcmd_symbol = " [](bold green)"

[hostname]
ssh_only = false
format = "[$hostname]($style) "

[directory]
truncation_length = 2
style = 'bold blue'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'yellow'

[git_status]
ignore_submodules = true
format = '[(\[[($untracked$modified)](purple)[($conflicted)](red)[($staged)](green)[($ahead_behind$stashed)](cyan)\])](green)'
conflicted = 'x'
untracked = 'u'
modified = 'm'
staged = 's'
stashed = '≡'

# [git_status]
# ignore_submodules = true
# format = '[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed) ]($style)'
# style = 'cyan'
# conflicted = '​'
# untracked = '​'
# modified = '​'
# staged = '​'
# renamed = '​'
# deleted = '​'
# stashed = '≡'

[status]
disabled = false
style = 'red'
format = '[$status ↵]($style)'

[python]
format = '[(\($virtualenv\)) ]($style)'

[time]
disabled = false
format = '[$time]($style) '
style = 'bold green'
time_format = '%T'
