export DOTFILES="$HOME/.dotfiles"

function sife() { [ -f $1 ] && source $1 }
source $DOTFILES/shell/path.zsh


if ! type "nvim" > /dev/null; then
  export EDITOR=vim
  export MANPAGER="sh -c \"col -b | vim --not-a-term -c 'set ft=man ts=8 nomod nolist nonu' \
    -c 'nnoremap i <nop>' \
    -c 'nnoremap <Space> <C-f>' \
    -c 'noremap q :quit<CR>' -\""
else
  export EDITOR=nvim
  export MANPAGER='nvim +Man!'
fi

export FZF_DEFAULT_COMMAND='rg --files --hidden'

# -- Plugins --
if ! type "antibody" > /dev/null; then
  $DOTFILES/shell/get_antibody.sh -b $HOME/.local/bin
fi

source <(antibody init)
antibody bundle <<BUNDLE
ohmyzsh/ohmyzsh
ohmyzsh/ohmyzsh path:plugins/z
ohmyzsh/ohmyzsh path:plugins/fzf
ohmyzsh/ohmyzsh path:plugins/sudo
ohmyzsh/ohmyzsh path:plugins/docker
ohmyzsh/ohmyzsh path:plugins/docker-compose
ohmyzsh/ohmyzsh path:plugins/kubectl
zsh-users/zsh-autosuggestions
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-completions
BUNDLE

# theme
source $DOTFILES/shell/zsh-prompt.zsh-theme

# source if exists
function sife() { [ -f $1 ] && source $1 }

sife $DOTFILES/shell/alias.zsh
sife $DOTFILES/shell/functions.zsh
sife $DOTFILES/shell/op.zsh

bindkey '^E' autosuggest-accept
bindkey '^ ' forward-word

unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}


# Disable command auto-correction.
export ENABLE_CORRECTION=false
export DISABLE_AUTO_TITLE=true

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
[ -f /usr/local/bin/mc ] && complete -o nospace -C /usr/local/bin/mc mc

# -- Sources --
sife $HOME/.zshrc.local

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

