export DOTFILES="$HOME/.dotfiles"

# source if exists
function sife() { [ -f $1 ] && source $1 }

sife $DOTFILES/shell/path.zsh
sife $DOTFILES/shell/alias.zsh
sife $DOTFILES/shell/functions.zsh
sife $DOTFILES/shell/pms.zsh
sife $DOTFILES/shell/op.zsh
sife $DOTFILES/shell/plugins/plugins.zsh


if ! type nvim > /dev/null; then
  export EDITOR=vim
  export MANPAGER="sh -c \"col -b | vim --not-a-term -c 'set ft=man ts=8 nomod nolist nonu' \
    -c 'nnoremap i <nop>' \
    -c 'nnoremap <Space> <C-f>' \
    -c 'noremap q :quit<CR>' -\""
else
  export EDITOR=nvim
  export MANPAGER='nvim +Man!'
fi

export FZF_DEFAULT_COMMAND='rg --files --hidden'

# keybinds
bindkey -v
bindkey '^ ' forward-word
bindkey '^[[1;5C' forward-word                    # ctrl + ->
bindkey '^[[1;5D' backward-word                   # ctrl + <-
bindkey '^[[1;3C' forward-word                    # alt + ->
bindkey '^[[1;3D' backward-word                   # alt + <-

# Disable command auto-correction.
unsetopt correct


HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=$HISTSIZE

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

# -- overrides --
sife $HOME/.zshrc.local

if ! type starship >> /dev/null; then
  echo 'installing starship'
  curl -sS https://starship.rs/install.sh | sh
fi

eval $(starship init zsh)
