#!/bin/bash
FILES=$(git ls-files -m)
for FILE in $FILES
do
    git diff $FILE
    read -r -p "Add $FILE? [y/N] " response
    response=${response,,}    # tolower
    if [[ $response =~ ^(yes|y)$ ]]
    then
        git add $FILE
        echo "Added $FILE"
    fi
done
