#!/bin/bash
youtube-dl -o .video $1
mplayer .video
read -p "Keep video?" yn
case $yn in
        [Yy]*) 
                mv .video downloaded_video
                ;;
        *) 
                rm .video
                ;;
esac
