#!/bin/bash
if hash zsh 2>/dev/null; then
  echo "zsh"
  rm -rf  $HOME/.zshrc
  ln -s $HOME/.dotfiles/shell/zshrc $HOME/.zshrc
  touch $HOME/.zshrc.local

  # vim
  echo "vim"
  rm -rf  $HOME/.vimrc $HOME/.vim
  ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
  ln -s $HOME/.dotfiles/vim $HOME/.vim
  mkdir -p $HOME/.config
  ln -s $HOME/.dotfiles/vim $HOME/.config/nvim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
  echo "install zsh please"
fi
