#!/bin/bash
if hash zsh 2>/dev/null; then
bash <(curl -s https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)

echo "zsh"
rm -rf  $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/zshrc $HOME/.zshrc
touch $HOME/.zshrc.local

# vim
echo "vim"
rm -rf  $HOME/.vimrc $HOME/.vim
ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
ln -s $HOME/.dotfiles/vim $HOME/.vim
else
  echo "install zsh"
fi
